version: '1.0'
services:

  leadgen:
    container_name: leadgen
    image: leadgen
    build:
      context: ..
      dockerfile: /deployments/Dockerfile
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: