definitions:
  Building.Building:
    properties:
      city:
        type: string
      id:
        type: integer
      level:
        type: integer
      name:
        type: string
      year:
        type: integer
    type: object
  api.AddSuccess:
    properties:
      id:
        type: integer
    type: object
  api.ErrorResp:
    properties:
      error:
        type: string
    type: object
info:
  contact:
    name: Константин
    url: https://t.me/London68
  description: Тестовое задание.
  title: Leadgen
  version: "1.0"
paths:
  /building/:
    post:
      operationId: building-handler-add
      parameters:
      - description: Название_записи
        in: formData
        name: name
        required: true
        type: string
      - description: Населенный пункт
        in: formData
        name: city
        required: true
        type: string
      - description: Год
        in: formData
        name: year
        type: integer
      - description: Этажность
        in: formData
        name: level
        type: integer
      produces:
      - application/json
      - multipart/form-data
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.AddSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResp'
      summary: Добавляет Строение, возвращает уникальный номер
  /buildings/:
    get:
      operationId: building-handler-get
      parameters:
      - description: id
        in: query
        name: id
        type: integer
      - description: Название_записи
        in: query
        name: name
        type: string
      - description: Населенный пункт
        in: query
        name: city
        type: string
      - description: Год
        in: query
        name: year
        type: integer
      - description: Этажность
        in: query
        name: level
        type: integer
      produces:
      - application/json
      - multipart/form-data
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/Building.Building'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResp'
      summary: Получает Все объекты с базы. Есть фильтрация
swagger: "2.0"
